<?php

function assignment_help_get_student_post_form() {
  $module_path = drupal_get_path('module', 'assignment_help');

  drupal_add_js($module_path . '/js/handlecounter.js');
  drupal_add_js($module_path . '/js/assignment_help.js');
  drupal_add_css($module_path . '/css/post-help.css');

  $form = drupal_get_form('student_assignment_help_post_form');
  $output = drupal_render($form);

  return $output;
}

/**
 * Form builder to prepare
 */
function student_assignment_help_post_form($form,$form_state)
{
  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Youe Email Id'),
    '#attributes' => array('placeholder' => 'Enter Email')
  );

  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Your Subject'),
    '#attributes' => array('placeholder' => 'Enter Subject'),
  );

  $form['no_of_pages'] = array(
   '#type' => 'textfield',
   '#title' => t('Number of pages/words you require'),
   '#attributes' => array('id' => 'noofpages'),
   '#disabled' => true,
   '#default_value' => 1
  );

  $form['date'] = array(
    '#type' => 'date_popup',
    '#size' => 26,
    '#date_format' => variable_get('date_format_short', 'm/d/Y - H:i'),
    '#default_value' => '',
    '#prefix' => '<div class="col1">',
    '#suffix' => '</div>',
    '#required' => true,
  );

  //'#title' => t('Choose your assignment deadline'),


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Free Assistance'
  );

  return $form;
}

function student_assignment_help_post_form_submit($form, $form_state) {
  $values = $form_state['values'];
  $to = 'contact@anyassignmenthelp.com';
  $from = $values['mail'];

  // Get the to and from e-mail addresses.
  $values['message'] = "Need Help In : ".$values['Subject'] . " having ". $values['no_of_pages'] ." pages before " . $values['date'];

  drupal_mail('assignment_help', 'free_assistace', $to, language_default(), $values, $from);
  drupal_goto($path);
}

/**
 * Implements hook_theme().
 */
function assignment_help_theme()
{
  $themes = array();

  $themes['student_assignment_help_post_form'] = array(
    'render element' => 'form',
    'template' => 'templates/student-assignment-help-post-form'
  );

  return $themes;
}

function assignment_help_menu(){
    $items ['assignment-help/order-now'] = array(
      'page callback' => 'assignment_help_order_now',
      'access callback' => true,
      'delivery callback' => 'ajax_deliver',
      'theme callback' => 'ajax_base_page_theme',
      'type' => MENU_CALLBACK,
      'file' => 'include/assignment_help_order_now.inc'
  );
    
    return $items;
}


